export const SET_USER = 'SET_USER'
export const SET_CART = 'SET_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const SET_INSTA = 'SET_INSTA'
export const CLEAR_INSTA = 'CLEAR_INSTA'
export const SET_EMAIL = 'SET_EMAIL'
export const CLEAR_EMAIL = 'CLEAR_EMAIL'
